name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1 
  permission_handler: ^12.0.0+1
  call_log: ^5.0.5
  flutter_phone_direct_caller: ^2.2.1
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  hexcolor: ^3.0.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  phone_state: ^2.1.1
  flutter_svg: ^2.1.0
  whatsapp: ^3.0.0
  flutter_contacts: ^1.1.9+2
  get: ^4.7.2
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.13.1
  flutter_overlay_window: ^0.5.0
  file_picker: ^10.1.9
  path: ^1.9.1
  flutter_image_compress: ^2.4.0
  http_parser: ^4.1.2
  path_provider: ^2.1.5
  fl_chart: ^1.0.0
  speech_to_text: ^7.0.0
  dropdown_search: ^6.0.2
  firebase_messaging: ^15.2.9
  flutter_callkit_incoming: ^2.5.8
  uuid: ^4.5.1
  # flutter_background: ^1.3.0+1
  # flutter_background_service: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/en.json
    - assets/mr.json
    - assets/hn.json

  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
