// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2mshMQg0tfbioBS6a0Gu8kbImoX4ZOK8',
    appId: '1:548843785853:web:c56f76529aadbed042eb14',
    messagingSenderId: '548843785853',
    projectId: 'pawanputranotification',
    authDomain: 'pawanputranotification.firebaseapp.com',
    storageBucket: 'pawanputranotification.firebasestorage.app',
    measurementId: 'G-8QZ3688CZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAssPIT7RwaVfI0xFEAYlouIgb62QeeIXY',
    appId: '1:548843785853:android:ad8ce5365ecba59142eb14',
    messagingSenderId: '548843785853',
    projectId: 'pawanputranotification',
    storageBucket: 'pawanputranotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslNQjyK8Tfs8ZKBUJK2PXRkyCycYQRwo',
    appId: '1:548843785853:ios:ff2a9d95b279f7c142eb14',
    messagingSenderId: '548843785853',
    projectId: 'pawanputranotification',
    storageBucket: 'pawanputranotification.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCslNQjyK8Tfs8ZKBUJK2PXRkyCycYQRwo',
    appId: '1:548843785853:ios:ff2a9d95b279f7c142eb14',
    messagingSenderId: '548843785853',
    projectId: 'pawanputranotification',
    storageBucket: 'pawanputranotification.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2mshMQg0tfbioBS6a0Gu8kbImoX4ZOK8',
    appId: '1:548843785853:web:4cdb22932869dce042eb14',
    messagingSenderId: '548843785853',
    projectId: 'pawanputranotification',
    authDomain: 'pawanputranotification.firebaseapp.com',
    storageBucket: 'pawanputranotification.firebasestorage.app',
    measurementId: 'G-3GH7L6HH30',
  );

}